import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader
          color="#155dfc"
          initialPosition={0.2}
          crawlSpeed={200}
          height={5}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={100}
          shadow="0 0 10px #155dfc, 0 0 5px #4f39f6"
          template={`
            <style>
              .bar {
                background: linear-gradient(90deg, #155dfc, #4f39f6);
                border-radius: 100%;
                box-shadow: 0 0 10px #155dfc, 0 0 5px #4f39f6;
                height: 100%;
              }
              .peg {
                display: none;
              }
              .spinner-icon {
                display: none;
                width: 18px;
                height: 18px;
                border: 2px solid transparent;
                border-top-color: #155dfc;
                border-left-color: #4f39f6;
                border-radius: 100%;
                animation: spin 400ms linear infinite;
                box-shadow: 0 0 6px #155dfc, 0 0 4px #4f39f6;
              }
              @keyframes spin {
                to { transform: rotate(360deg); }
              }
            </style>
            <div class="bar" role="bar"></div>
            <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>
          `}
          zIndex={1600}
          showAtBottom={false}
        />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
